src/Entity/Agence.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgenceRepository")
 * @Vich\Uploadable()
 */
class Agence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="BuyAndRent_images", fileNameProperty="imageAgence")
     *
     * @var File|null
     * @Assert\Image(
     *     mimeTypes = { "image/png",   "image/jpeg", "image/jpg" })
     * ])
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Votre adresse doit être au moins  {{ limit }} caractères",
     *      maxMessage = "Votre adresse doit être  au plus {{ limit }} caractères"
     * )
     * @Assert\NotBlank
     */
    private $denomination;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *      min = 10,
     *      max = 5000,
     *      minMessage = "Votre description doit contenir au moins {{ limit }} caractères",
     *      maxMessage = "Votre description doit contenir au plus{{ limit }} caractères"
     * )
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message = "Cette adresse email n'est pas valide.")
     * @Assert\NotBlank
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{10}$/",
     *  message="Le numero de téléphone doit être de sur ce format : 0625154078"
     * )
     * @Assert\NotBlank
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Votre adresse doit être au moins  {{ limit }} caractères",
     *      maxMessage = "Votre adresse doit être  au plus {{ limit }} caractères"
     * )
     * @Assert\NotBlank
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/",
     * message="L'adresse postal doit contenir 5 chiffres exemple : 75000")
     * @Assert\NotBlank
     */
    private $codePostal;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "La ville doit être au moins  {{ limit }} caractères",
     *      maxMessage = "La ville doit être au  plus {{ limit }} caractères"
     * )
     * @Assert\NotBlank
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageAgence;

    /**
     * @ORM\Column(type="datetime" , nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur_2;


    public function __construct()
    {
        $this->setCreatedAt(new DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getImageAgence(): ?string
    {
        return $this->imageAgence;
    }

    public function setImageAgence(?string $imageAgence): void
    {
        $this->imageAgence = $imageAgence;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * Get nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * Set nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @param  File|null  $imageFile  NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  self
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }
    public function getCouleur1(): ?string
    {
        if ($this->couleur_1 == null) {
            $this->couleur_1 = "#b4cc83";
        }
        return $this->couleur_1;
    }

    public function setCouleur1(?string $couleur_1): self
    {
        $this->couleur_1 = $couleur_1;
        return $this;
    }

    public function getCouleur2(): ?string
    {
        if ($this->couleur_2 == null) {
            $this->couleur_2 = "#154854";
        }
        return $this->couleur_2;
    }

    public function setCouleur2(?string $couleur_2): self
    {
        $this->couleur_2 = $couleur_2;

        return $this;
    }
}

src/Controller/appPro/AgenceController.php
<?php


namespace App\Controller\appPro;

use DateTime;
use App\Entity\Agence;
use App\Form\AgenceType;
use App\Repository\AgenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AgenceController extends AbstractController
{
    private $agenceRepository;
    private $entityManager;

    public function __construct(
        AgenceRepository $agenceRepository,
        EntityManagerInterface $entityManager
    ) {
        $this->agenceRepository = $agenceRepository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/admin/info", name="info_agence")
     *
     * @param Agence $agence
     * @return Response
     */
    public function showAgence(): Response
    {
        $agence = $this->agenceRepository->findAll();
        return $this->render('appPro/agence/show_agence.html.twig', [

            'slug' => 'info_agence',
            'agence' => $agence[0],
        ]);
    }


    /**
     * @Route("/admin/edit-agence-{id}", name="edit_agence", methods={"GET|POST"})
     *
     * editerAgence (Editer les informations de l'agence)
     * @param Agence $agence
     * @param Request $request
     * @return Response
     */
    public function editerAgence(
        Agence $agence,
        Request $request,
        CacheManager $cacheManager,
        UploaderHelper $helper
    ): Response {
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //Vidé l'image dans le cache avant la mise à jour
            if ($agence->getImageFile() instanceof UploadedFile) {
                $cacheManager->remove($helper->asset($agence, 'imageFile'));
            }
            $agence->setUpdatedAt(new DateTime());
            $this->entityManager->flush();
            $this->addFlash('success', "Le produit à bien été mis à jour");

            return $this->redirectToRoute('info_agence');
        }

        return $this->render('appPro/agence/edit_agence.html.twig', [

            'slug' => 'edit_agence',
            'agence' => $agence,
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/appPro/ArchivesController.php
<?php

declare(strict_types=1);

namespace App\Controller\appPro;

use DateTime;
use App\Entity\Biens;
use App\Entity\Agence;
use App\Form\AgenceType;
use App\Repository\BiensRepository;
use App\Repository\AgenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use phpDocumentor\Reflection\Types\Null_;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArchivesController extends AbstractController
{
    /**
     * @Route("/admin/archives", name="archives")
     */
    public function archiveBien(
        BiensRepository $biensRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $lengthBiens = $biensRepository->biensArchives();
        //Ajouter une pagination à la liste de nos biens et filtrer si possible
        $data = $biensRepository->biensArchives();

        $biens = $paginator->paginate(
            $data, //On passe les données
            $request->query->getInt('page', 1), //Numéro de la pasge en cours, 1 par défaut
            10 //Nombre d'élement par page
        );


        return $this->render('appPro/archives.html.twig', [
            'slug' => 'info_agence',
            'biens' => $biens,
            'lengthBiens' => $lengthBiens,
        ]);
    }

    /**
     * @Route("/admin/archives/supprimer-bien/{id}", name="supprimer_bien", methods={"GET"})
     * @param Biens $bien
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function supprimierBien(Biens $bien, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($bien);
        $entityManager->flush();
        $this->addFlash('success', "La catégorie a bien été définitivement supprimée de la base de données");

        return $this->redirectToRoute('archives');
    }
    /**
     * @Route("/restaurer-produit/{id}", name="restaurer_produit_pro", methods={"GET"})
     * @param Biens $bien
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function softDeleteArticle(Biens $bien, EntityManagerInterface $entityManager): Response
    {
        $bien->setDeletedAt(null);

        $entityManager->persist($bien);
        $entityManager->flush();
        $this->addFlash('success', "Bien restauré avec succès 👍");

        return $this->redirectToRoute('liste_produit_pro');
    }
}

src/Controller/appPro/ClientController.php
<?php

namespace App\Controller\appPro;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/liste/", name="client_liste", methods={"GET"})
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function afficherClients(): Response
    {
        return $this->render('appPro/client/liste.html.twig', [
            'slug' => 'client_liste'
        ]);
    }
}

src/Controller/appPro/DossierController.php
<?php

namespace App\Controller\appPro;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/dossier")
 */
class DossierController extends AbstractController
{
    /**
     * @Route("/liste/", name="dossier_liste_pro", methods={"GET"})
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function listedossiers(): Response
    {
        return $this->render('appPro/dossier/liste.html.twig', [
            'slug' => 'dossier_liste_pro'

        ]);
    }
    /**
     * @Route("/afficher/", name="dossier_afficher_pro", methods={"GET"})
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function afficherdossiers(): Response
    {
        return $this->render('appPro/dossier/afficher.html.twig', [
            'slug' => 'dossier_afficher_pro'

        ]);
    }
}

src/Controller/appPro/OptionController.php
<?php

namespace App\Controller\appPro;

use App\Entity\Option;
use App\Form\OptionType;
use App\Repository\OptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/option")
 */
class OptionController extends AbstractController
{
    /**
     * @Route("/liste", name="creer_option_pro", methods={"GET","POST"})
     */
    public function creer(
        EntityManagerInterface $entityManager,
        Request $request,
        OptionRepository $optionRepository
    ): Response {
        $option = new Option();
        $form = $this->createForm(OptionType::class, $option);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($option);
            $entityManager->flush();
            $this->addFlash('success', "L'option a été crée avec succès' 👍");

            return $this->redirectToRoute('creer_option_pro');
        }

        return $this->render('appPro/option/creer_option.html.twig', [
            'options' => $optionRepository->findAll(),
            'slug' => 'creer_option_pro',
            'option' => $option,
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/editer/{id}", name="editer_option_pro", methods={"GET","POST"})
     */
    public function editer(
        EntityManagerInterface $entityManager,
        Request $request,
        Option $option
    ): Response {
        $form = $this->createForm(OptionType::class, $option);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', "L'option a été modifié avec succès' 👍");

            return $this->redirectToRoute('creer_option_pro');
        }

        return $this->render('appPro/option/editer_option.html.twig', [
            'slug' => 'creer_option_pro',
            'option' => $option,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer_option_pro", methods={"GET"})
     */
    public function delete(EntityManagerInterface $entityManager, Option $option): Response
    {
        $entityManager->remove($option);
        $entityManager->flush();
        $this->addFlash('success', "L'option a été supprimé avec succès' 👍");


        return $this->redirectToRoute('creer_option_pro');
    }
}

templates/appPro/paramettre/interface.html.twig
{% extends 'appPro/layout.html.twig' %} {% block title %} {% endblock %} {% block content %}
<section class="pt-4 h-100" id="content-wrapper" style="width:100%!important;height:1000px!important">
    <div class="container">
        <ul class="nav nav-tabs bg-white text-uppercase">
            <li class="nav-item bg_primary border-0">
                <a class="nav-link bg_primary text-light" href="{{path('')}}">Paramettre de l'nterface</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text_primary"  href="{{path('admin_ajouter_agent')}}">Utilisateurs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text_primary" href="#">Documents</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-danger disabled" href="#">Confidentiel</a>
            </li>
        </ul>
        <div class="row mt-5">
            <div class="col-md-7">
                <div class="card p-3" style="background-color:#f6f6f6">
                    <p class="font2 text-uppercase"> Prévisulation de l'interface </p><br>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="text-light text-center" style="background-color:{{agence.couleur1}}"> LOGO </div>
                            <div class="" style="height:250px;background-color:{{agence.couleur2}}"> <hr> <hr><hr></div>
                        </div>
                        <div class="col-md-9">
                            <div class=" w-100 bg_white text-dark">
                                <div class="float:left">
                                    <span class="badge" style="background-color:{{agence.couleur1}}">1</span>
                                    <span class="badge" style="background-color:{{agence.couleur1}}">2</span>
                                    <span class="badge" style="background-color:{{agence.couleur1}}">3</span>
                                    <span class="badge" style="background-color:{{agence.couleur1}}">4</span> 
                                    <span class="badge text-muted" style="background-color:lightgray;width:200px"><small>Recherche rapide </small></span> 
                                    {# <input type="text" id="inputColor1" class="inputColor1">test</input> #}
                                </div>
                            </div>
                            <div class="mt-3" style="background-color:lightgray;height:250px"> Contenu
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                {{form_start(form, {'attr': {novalidate: 'novalidate'}})}} 
                <div class="row align-items-center">
                    <div class="col-md-11">
                    <label><small>&nbsp;&nbsp; Cliquez pour choisir la première couleur</small> </label>
                        {{ form_row(form.couleur_1,{'attr': {'class': 'radius10 text2 formCouleur1'}}) }}
                    </div>
                    {# <div class="col-md-1">
                        <div class="btn bg_secondary text-light radius10"><i class="fas fa-sync"></i></div>
                    </div> #}
                </div>
                <div class="row mt-4 align-items-center">
                    <div class="col-md-11">

                        <span class="color-picker">
                            <label for="colorPicker">
                                <input type="color" value="#1DB8CE" id="colorPicker">
                            </label>
                        </span>

                        {# <input class="inputColorTot" type="color" id="colorpicker" name="color" pattern="^#+([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$" value="#bada55"> 
 
                        <input class="colorInput inputColorTot" type="text" pattern="^#+([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$" value="#bada55" id="hexcolor"></input> #}
                        {# <ul class="list-group list-group-flush">
                            <li class="list-unstyled">
                                <div class="row">
                                    <div class="col-md-15">
                                        <label class="w-100 label_color">
                                            <input class="color form-control-file color_ajoutVoiture" id="color_ajoutVoiture" name="background_seller" placeholder="Color" data-value="#xxxxxx" value=""/>
                                        </label> 
                                    </div>
                                </div>
                            </li>
                        </ul> #}
                        {# <label><small>&nbsp;&nbsp;Cliquez pour choisir la seconde couleur</small> </label> #}
                        {# {{ form_row(form.couleur_2,{'attr': {'class': 'radius10 text2'}}) }} #}
                        {# {{ dump(form.couleur_1.vars.value)}} #}
                    </div>
                    {# <div class="col-md-1">
                        <div class="btn bg_secondary text-light radius10"><i class="fas fa-sync"></i></div>
                    </div> #}
                </div>
                <br>
                <div class="row mt-3 align-items-center">
                    <div class="col-md-6">
                        <button type="button" onclick="btn_previsualiserCouleur()" class="w-100 btn bg_primary text-dark radius10 text1 text-uppercase"> PRÉVISUALISER</button>
                     </div>
                     <div class="col-md-5">
                        <button type="submit" class="w-100 btn bg_primary text-dark radius10 text1 text-uppercase"> ENREGISTRER</button>
                     </div>
                 </div>
                  {{ form_end(form)}}
            </div>
            
           
        </div>
     
    </div>
</section>  

<style>

code {
  padding: 5px 8px;
  border-radius: 10px;
  background-color: #f8f9f9;
  color: #CC0066;
}

[type='color'] {
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;
  padding: 0;
  width: 15px;
  height: 15px;
  border: none;
}

[type='color']::-webkit-color-swatch-wrapper {
  padding: 0;
}

[type='color']::-webkit-color-swatch {
  border: none;
}

.color-picker {
  padding: 10px 15px;
  border-radius: 10px;
  border: 1px solid #ccc;
  background-color: #f8f9f9;
}


/* .inputColorTot{
  display: block;
  width: 50%;
  float: left;
  height: 80px;
}

.colorInput{
  padding: 20px;
}

.colorInput:invalid{
  outline: 2px solid red;
} */


/* 
.label_color{
    font-family: sans-serif;
    width: 300px;
    display: block;
    position: relative;
}

.color_ajoutVoiture{
    padding: 5px 15px;
    font-size: 16px;
    width: 100%;
    box-sizing: border-box;
    padding: 0;
    border: 0;
    height: 40px;
    padding-left: 10px;
}

.color_ajoutVoiture:after {
    content: attr(data-value);
    position: absolute;
    bottom: 10px;
    text-align: center;
    color: #fffff5;
    display: block;
    width: 100%;
}

.color-icon {
    position: absolute;
    bottom: 10px;
    right: 10px;
    color: #666;
    cursor: pointer;
} */

</style>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>

    document.querySelectorAll('input[type=color]').forEach(function(picker) {

  var targetLabel = document.querySelector('label[for="' + picker.id + '"]'),
    codeArea = document.createElement('span');
    // codeArea2 = document.getElementByClassName('formCouleur1');

  codeArea.innerHTML = picker.value;
  targetLabel.appendChild(codeArea);

  picker.addEventListener('change', function() {
    codeArea.innerHTML = picker.value;
    targetLabel.appendChild(codeArea);
  });
});

// $('#colorpicker').on('input', function() {
// 	$('#hexcolor').val(this.value);
// });
// $('#hexcolor').on('input', function() {
//   $('#colorpicker').val(this.value);
// });


// window.onload = function(){
//     $("input.color").each(function() {
//         var that = this;
//         $(this).parent().prepend($("<i class='fa fa-paint-brush color-icon'></i>").click(function() {
//             that.type = (that.type == "color") ? "text" : "color";
//     }));
//     }).change(function() {
//         $(this).attr("data-value", this.value);
//         this.type = "text";
//     });
// }
    

    </script>
{% endblock %}